"""
core/whatsapp_client.py — Telegram Bot sender for RepoRadar daily reports.
"""

import logging
import requests
from config.settings import TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID

logger = logging.getLogger(__name__)

REEL_PREVIEW_LENGTH = 350
TELEGRAM_API = "https://api.telegram.org/bot{token}/sendMessage"


def format_report(selected_repos, generated_content):
    lines = ["<b>🔭 RepoRadar Daily Report</b>", ""]
    content_by_repo_id = {c["repo_id"]: c for c in generated_content if c.get("repo_id")}

    for i, repo in enumerate(selected_repos, start=1):
        content = content_by_repo_id.get(repo.get("id", ""), {})
        reel = content.get("reel_script", "")

        lines += [
            "──────────────────────────",
            f"<b>{i}. {repo.get('full_name')}</b>",
            f"🔗 {repo.get('url')}",
            f"⭐ {repo.get('stars_current', 0):,} stars | ⚡ Velocity: {repo.get('velocity_score', 0):.1f}",
            f"📊 Virality {content.get('virality_score', '?')} · Learning {content.get('learning_score', '?')} · Innovation {content.get('innovation_score', '?')}",
            f"🏆 Overall: {content.get('overall_score', '?')}/100",
            "",
            "📱 <b>Reel Script:</b>",
            reel.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"),
            "",
        ]

    lines += ["──────────────────────────", "<i>Generated by RepoRadar 🤖</i>"]
    return "\n".join(lines)


def format_empty_report():
    return "<b>🔭 RepoRadar Daily Report</b>\n\n😴 Nothing remarkable found today.\nAll repos failed velocity/quality filters.\n\n<i>Generated by RepoRadar 🤖</i>"


def send_whatsapp(message: str) -> bool:
    """Send message via Telegram Bot. Returns True on success."""
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        logger.warning("[Telegram] Bot token or chat ID not configured. Skipping send.")
        return False
    try:
        resp = requests.post(
            TELEGRAM_API.format(token=TELEGRAM_BOT_TOKEN),
            json={
                "chat_id": TELEGRAM_CHAT_ID,
                "text": message,
                "parse_mode": "HTML",
            },
            timeout=15,
        )
        resp.raise_for_status()
        logger.info(f"[Telegram] Message sent successfully.")
        return True
    except Exception as e:
        logger.error(f"[Telegram] Failed to send message: {e}")
        return False
