"""
core/whatsapp_client.py — Telegram Bot sender for RepoRadar daily reports.
"""

import logging
from datetime import datetime, timezone

import requests
from config.settings import TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID

logger = logging.getLogger(__name__)

TELEGRAM_API = "https://api.telegram.org/bot{token}/sendMessage"

PILLAR_EMOJI = {
    "workflow":         "⚙️",
    "roadmap":          "🗺️",
    "comparison":       "⚖️",
    "problem_solution": "🔧",
    "hidden_problem":   "🐛",
    "trend_report":     "📈",
}

PILLAR_LABEL = {
    "workflow":         "Workflow Template",
    "roadmap":          "Developer Roadmap",
    "comparison":       "Tool Comparison",
    "problem_solution": "Problem → Solution Map",
    "hidden_problem":   "Hidden Problem",
    "trend_report":     "Weekly Trend Report",
}


def _safe(text: str) -> str:
    """Escape HTML special characters in user-generated text."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def format_report(selected_repos: list, generated_content: list, pillar_content: list | None = None) -> str:
    today = datetime.now(timezone.utc).strftime("%b %d, %Y")
    lines = [f"<b>🔭 RepoRadar Daily — {today}</b>", ""]

    # ── Section 1: Repo Finds ─────────────────────────────────────────────────
    lines += ["<b>━━━━━━━━━━━━━━━━━━━━━━━━</b>",
              "<b>📦 TODAY'S REPO FINDS</b>",
              "<b>━━━━━━━━━━━━━━━━━━━━━━━━</b>", ""]

    content_by_repo_id = {c["repo_id"]: c for c in generated_content if c.get("repo_id")}

    for i, repo in enumerate(selected_repos, start=1):
        content = content_by_repo_id.get(repo.get("id", ""), {})
        reel = content.get("reel_script", "")

        lines += [
            f"<b>{i}. {_safe(repo.get('full_name', '?'))}</b>",
            f"🔗 {repo.get('url', '')}",
            f"⭐ {repo.get('stars_current', 0):,} stars | ⚡ Velocity: {repo.get('velocity_score', 0):.1f}",
            f"📊 Virality {content.get('virality_score', '?')} · Learning {content.get('learning_score', '?')} · Innovation {content.get('innovation_score', '?')}",
            f"🏆 Overall: {content.get('overall_score', '?')}/100",
            "",
            "📱 <b>Reel Script:</b>",
            _safe(reel),
            "──────────────────────────",
            "",
        ]

    if not selected_repos:
        lines += ["😴 Nothing remarkable found today.\n", "──────────────────────────", ""]

    # ── Section 2: Pillar Content ─────────────────────────────────────────────
    if pillar_content:
        pillar = pillar_content[0]
        pillar_type = pillar.get("pillar", "")
        emoji = PILLAR_EMOJI.get(pillar_type, "🎯")
        label = PILLAR_LABEL.get(pillar_type, "Content")
        theme = pillar.get("theme", "")
        hook = pillar.get("hook", "")
        slides = pillar.get("slides", [])
        caption = pillar.get("caption", "")

        lines += [
            "<b>━━━━━━━━━━━━━━━━━━━━━━━━</b>",
            f"<b>{emoji} TODAY'S ORIGINAL CONTENT</b>",
            "<b>━━━━━━━━━━━━━━━━━━━━━━━━</b>",
            "",
            f"<b>Pillar:</b> {label}",
            f"<b>Theme:</b> {_safe(theme)}",
            f"<b>Hook:</b> {_safe(hook)}",
            "",
            "<b>Slides:</b>",
        ]

        for slide in slides:
            num = slide.get("slide_num", "?")
            headline = _safe(slide.get("headline", ""))
            body = _safe(slide.get("body", ""))
            visual = _safe(slide.get("visual_cue", ""))
            lines.append(f"  <b>{num}.</b> {headline}")
            lines.append(f"       {body}")
            if visual:
                lines.append(f"       📷 <i>{visual}</i>")

        lines += [
            "",
            "<b>Caption:</b>",
            _safe(caption),
            "──────────────────────────",
        ]

    lines.append("<i>Generated by RepoRadar 🤖</i>")
    return "\n".join(lines)


def format_empty_report() -> str:
    today = datetime.now(timezone.utc).strftime("%b %d, %Y")
    return (
        f"<b>🔭 RepoRadar Daily — {today}</b>\n\n"
        "😴 Nothing remarkable found today.\n"
        "All repos failed velocity/quality filters.\n\n"
        "<i>Generated by RepoRadar 🤖</i>"
    )


def send_whatsapp(message: str) -> bool:
    """Send message via Telegram Bot. Returns True on success."""
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        logger.warning("[Telegram] Bot token or chat ID not configured. Skipping send.")
        return False

    # Telegram message length limit is 4096 chars
    if len(message) > 4096:
        message = message[:4090] + "\n[…]"

    try:
        resp = requests.post(
            TELEGRAM_API.format(token=TELEGRAM_BOT_TOKEN),
            json={
                "chat_id": TELEGRAM_CHAT_ID,
                "text": message,
                "parse_mode": "HTML",
            },
            timeout=15,
        )
        resp.raise_for_status()
        logger.info("[Telegram] Message sent successfully.")
        return True
    except Exception as e:
        logger.error(f"[Telegram] Failed to send message: {e}")
        return False
