"""
core/whatsapp_client.py — Twilio WhatsApp API sender and report formatter for RepoRadar.
"""

import logging
from typing import Any

from twilio.rest import Client as TwilioClient

from config.settings import (
    TWILIO_SID,
    TWILIO_AUTH_TOKEN,
    TWILIO_WHATSAPP_FROM,
    WHATSAPP_TO,
)

logger = logging.getLogger(__name__)

REEL_PREVIEW_LENGTH = 350  # Keep under Twilio's 1600-char message limit (3 repos × ~350 + headers ≈ 1400)


def format_report(
    selected_repos: list[dict[str, Any]],
    generated_content: list[dict[str, Any]],
) -> str:
    """
    Build a formatted WhatsApp message string from selected repos and their content.

    selected_repos: list of repo dicts (with velocity_score, stars_current, full_name, url)
    generated_content: list of content dicts (with reel_script, virality_score, etc.)
                       — indexed to match selected_repos order
    """
    lines: list[str] = ["🔭 *RepoRadar Daily Report*", ""]

    # Build a lookup: repo_id → content
    content_by_repo_id: dict[str, dict] = {
        c["repo_id"]: c for c in generated_content if c.get("repo_id")
    }

    for i, repo in enumerate(selected_repos, start=1):
        repo_id = repo.get("id", "")
        content = content_by_repo_id.get(repo_id, {})

        stars = repo.get("stars_current", 0)
        velocity = repo.get("velocity_score", 0.0)
        full_name = repo.get("full_name", "unknown/unknown")
        url = repo.get("url", f"https://github.com/{full_name}")

        virality = content.get("virality_score", "?")
        learning = content.get("learning_score", "?")
        innovation = content.get("innovation_score", "?")
        overall = content.get("overall_score", "?")
        reel_script = content.get("reel_script", "")

        # Truncate reel script for WhatsApp preview
        script_preview = reel_script[:REEL_PREVIEW_LENGTH]
        if len(reel_script) > REEL_PREVIEW_LENGTH:
            script_preview += "..."

        lines += [
            "──────────────────────────────",
            f"*{i}. {full_name}*",
            f"🔗 {url}",
            f"⭐ {stars:,} stars | ⚡ Velocity: {velocity:.1f}",
            f"📊 Virality {virality} · Learning {learning} · Innovation {innovation}",
            f"🏆 Overall: {overall}/100" if isinstance(overall, (int, float)) else f"🏆 Overall: {overall}",
            "",
            "📱 *Reel Script:*",
            script_preview,
            "",
        ]

    lines += [
        "──────────────────────────────",
        "_Generated by RepoRadar 🤖_",
    ]

    return "\n".join(lines)


def format_empty_report() -> str:
    """Message when no repos passed the pipeline today."""
    return (
        "🔭 *RepoRadar Daily Report*\n\n"
        "──────────────────────────────\n"
        "😴 Nothing remarkable found today.\n"
        "All discovered repos failed velocity/quality filters.\n"
        "──────────────────────────────\n"
        "_Generated by RepoRadar 🤖_"
    )


def send_whatsapp(message: str) -> bool:
    """
    Send a WhatsApp message via Twilio.
    Returns True on success, False on failure (pipeline continues regardless).
    """
    try:
        client = TwilioClient(TWILIO_SID, TWILIO_AUTH_TOKEN)
        msg = client.messages.create(
            body=message,
            from_=TWILIO_WHATSAPP_FROM,
            to=WHATSAPP_TO,
        )
        logger.info(f"[WhatsApp] Message sent. SID: {msg.sid}")
        return True
    except Exception as e:
        logger.error(f"[WhatsApp] Failed to send message: {e}")
        return False
